# RGBD Camera topics
- ros_topic_name: "/auv/camera/image"
  gz_topic_name: "/auv/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true # Determines whether connections are created immediately at startup (when false) or only when data is actually requested by a subscriber (when true), helping to conserve system resources at the cost of potential initial delays in data flow.


# - ros_topic_name: "cam_1/depth/color/points"
#   gz_topic_name: "cam_1/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "gz.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS
#   lazy: true



# IMU configuration
- ros_topic_name: "/auv/imu"
  gz_topic_name: "/auv/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false

# # Sending velocity commands from ROS 2 to Gazebo
# - ros_topic_name: "mecanum_drive_controller/cmd_vel"
#   gz_topic_name: "mecanum_drive_controller/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/TwistStamped"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
#   lazy: false

# Clock configuration
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

